/*
 * File: defaults.js
 * Project: cellcard-play-pwa
 * Author: Dilum Sanjaya (dranasinghe@mitrai.com)
 * File Created: Wednesday, 07th October 2020 05:54 pm
 * Module: Cellcard Play Frontend
 * Copyright 2020 - 2020 Mitra Innovation Ltd., Mitra Innovation Ltd.
 */

const defaults = {
  AWARD_CFMN2019: 'AWARD_CFMN2019',
  AWARD_CFMN2018: 'AWARD_CFMN2018',
  AWARD_BGE: 'AWARD_BGE',
  FOLLOW_FACEBOOK: 'FOLLOW_FACEBOOK',
  FOLLOW_YOUTUBE: 'FOLLOW_YOUTUBE',
  FOLLOW_INSTAGRAM: 'FOLLOW_INSTAGRAM',
  FOLLOW_TICKTOCK: 'FOLLOW_TICKTOCK',
  SECTION_FAQ: 'SECTION_FAQ',
  SECTION_SUPORT: 'SECTION_SUPORT',
  SECTION_PRIVACY: 'SECTION_PRIVACY',
  SECTION_TC: 'SECTION_TC',
  HAMBURGER_HOME: 'HAMBURGER_HOME',
  HAMBURGER_PLANS: 'HAMBURGER_PLANS',
  HAMBURGER_BUY_PLAY_POINTS: 'HAMBURGER_BUY_PLAY_POINTS',
  HAMBURGER_FAQS: 'HAMBURGER_FAQS',
  HAMBURGER_SUPPORT: 'HAMBURGER_SUPPORT',
  HAMBURGER_ABOUT: 'HAMBURGER_ABOUT',
};

export default defaults;
