/*
 * File: index.js
 * Project: cellcard-play-pwa
 * Author: Dilum Sanjaya (dranasinghe@mitrai.com)
 * File Created: Friday, 28th August 2020 09:49 am
 * Module: Cellcard Play Frontend
 * Copyright 2020 - 2020 Mitra Innovation Ltd., Mitra Innovation Ltd.
 */
import {
  STATUS_FAIL,
  STATUS_PENDING,
  STATUS_SUCCESS,
  STATUS_ERROR,
} from 'constants/Images';
import { ROUTE_STORE } from 'constants/Routes';

const ME = 'ME';
const PLAN = 'PLAN';
const SUCCESS = 'SUCCESS';

const DTU_CELLCARD_PENDING = {
  icon: STATUS_PENDING,
  title: 'GP_SYSTEMMESSAGES_PENDINGTITLE',
  description: 'GP_SYSTEMMESSAGES_TOPUPPURCHASEPENDINGCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};
const DTU_CELLCARD_SUCCESS = {
  icon: STATUS_SUCCESS,
  title: 'GP_SYSTEMMESSAGES_SUCCESSPURCHASETITLE',
  description: 'GP_SYSTEMMESSAGES_TOPUPPURCHASESUCCESSCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_BACKTOSTORE',
  btnMainLink: ROUTE_STORE,
};
const DTU_CELLCARD_FAILED = {
  icon: STATUS_FAIL,
  title: 'GP_SYSTEMMESSAGES_COULDNOTPURCHASETITLE',
  description: 'GP_NOTIFICATION_TOPUPPENDINGFAILCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};

const DV_GAME_PENDING = {
  icon: STATUS_PENDING,
  title: 'GP_SYSTEMMESSAGES_PENDINGTITLE',
  description: 'GP_SYSTEMMESSAGES_PENDINGCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};
const DV_GAME_SUCCESS = {
  icon: STATUS_SUCCESS,
  title: 'GP_SYSTEMMESSAGES_SUCCESSPURCHASETITLE',
  description: 'GP_SYSTEMMESSAGES_SUCCESSPURCHASECONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_VIEWVOUCHER',
  btnMainLink: ROUTE_STORE,
  btnSubTitle: 'GP_SYSTEMMESSAGES_BACKTOSTORE',
  btnSubLink: ROUTE_STORE,
};
const DV_GAME_FAILED = {
  icon: STATUS_FAIL,
  title: 'GP_SYSTEMMESSAGES_COULDNOTPURCHASETITLE',
  description: 'GP_SYSTEMMESSAGES_COULDNOTPURCHASECONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};

const DV_MERCHANDISE_PENDING = {
  icon: STATUS_PENDING,
  title: 'GP_SYSTEMMESSAGES_PENDINGTITLE',
  description: 'GP_SYSTEMMESSAGES_TOPUPPURCHASEPENDINGCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};
const DV_MERCHANDISE_SUCCESS = {
  icon: STATUS_SUCCESS,
  title: 'GP_SYSTEMMESSAGES_SUCCESSPURCHASETITLE',
  description: 'GP_SYSTEMMESSAGES_SUCCESSPURCHASECONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_VIEWVOUCHER',
  btnMainLink: ROUTE_STORE,
  btnSubTitle: 'GP_SYSTEMMESSAGES_BACKTOSTORE',
  btnSubLink: ROUTE_STORE,
};
const DV_MERCHANDISE_FAILED = {
  icon: STATUS_FAIL,
  title: 'GP_SYSTEMMESSAGES_COULDNOTPURCHASETITLE',
  description: 'GP_SYSTEMMESSAGES_TOPUPPURCHASEFAILCONTENT',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};
const PRODUCT_STATUS_ERROR = {
  icon: STATUS_ERROR,
  title: 'GP_SYSTEMMESSAGES_ERROROCCURRED',
  description: '',
  btnMainTitle: 'GP_SYSTEMMESSAGES_OKAY',
  btnMainLink: ROUTE_STORE,
};

const DEFAULT = 'PRODUCT_STATUS_ERROR';
const MAX_NUM_OF_TRIES = 10;
const DELAY_BETWEEN_TRIES = 1000;

export default {
  MAX_NUM_OF_TRIES,
  DELAY_BETWEEN_TRIES,
  PRODUCT_STATUS_ERROR,
  DEFAULT,
  ME,
  PLAN,
  SUCCESS,
  DTU_CELLCARD_PENDING,
  DTU_CELLCARD_SUCCESS,
  DTU_CELLCARD_FAILED,
  DV_GAME_PENDING,
  DV_GAME_SUCCESS,
  DV_GAME_FAILED,
  DV_MERCHANDISE_PENDING,
  DV_MERCHANDISE_SUCCESS,
  DV_MERCHANDISE_FAILED,
  STATUS_ERROR,
};
